name: OpenaiPineconeIndexer Tests

on: [pull_request]

jobs:
  test:
      runs-on: ubuntu-latest
            
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
              
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
                
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pytest einops lion-pytorch

      - name: Test with pytest
        env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest src/tests/openaiindex_test.py
        