name: CoherePineconeIndexer Tests

on: [pull_request]

jobs:
  test:
      runs-on: ubuntu-latest
            
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
              
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
                
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pytest einops lion-pytorch

      - name: Test CoherePineconeIndexer
        id: cohere_test
        env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          pytest src/tests/cohereindex_test.py


      - name: Test OpenaiPineconeIndexer
        id: openai_test
        env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest src/tests/openaiindex_test.py


      - name: Test GooglePineconeIndexer
        id: google_test
        env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          pytest src/tests/googleindex_test.py
      
        