name: Tests

on: [pull_request]

jobs:
  test:
      runs-on: ubuntu-latest
            
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
              
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
                
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pytest einops lion-pytorch

      - name: Test with pytest
        env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            COHERE_API_KEY : ${{ secrets.COHERE_API_KEY }}
        run: |
          export PYTHONPATH=$PYTHONPATH: /src
          pytest tests/test_pineconeindex_cohere.py tests/test_pineconeindex_google.py tests/test_pineconeindex_openai.py
        